<a href="https://colab.research.google.com/github/rajiv1817/NNDL/blob/main/NNDL_XOR_GATE_MULTILAYER_PERCEPTRON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.importing the nessary library

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import sys

2.define vector values in input and output

In [13]:
# The training data.
X = np.array([
[0, 0],
[0, 1],
[1, 0],
[1, 1]
])
# The labels for the training data.
y = np.array([
[0],
[1],
[1],
[0]
])


3.Define weights of the variable

In [14]:
W11 = np.asarray([1,1])
W12 = np.asarray([1,1])
W2 = np.asarray([-1,1])
B1 = np.asarray([-1.5,-0.5])
B2 = np.asarray([-0.5])

In [15]:
W11

array([1, 1])

In [16]:
W12

array([1, 1])

In [18]:
B2

array([-0.5])

In [19]:
W2

array([-1,  1])

In [20]:

B1

array([-1.5, -0.5])

In [21]:
x=X[0]
print(x)

[0 0]


In [22]:
len(W11)


2

In [27]:
def summation(x,Wt1,Wt2,Bs):
  sumh =[0,0]
  for i in range(len(x)):
    sumh [i]=(x[0]*Wt1[i]+x[1]*Wt2[i])+Bs[i]
  return sumh

In [28]:
sumv=summation(x,W11,W12,B1)


In [29]:
print(sumv)


[-1.5, -0.5]


In [30]:
def Heaviside (net):
  if net >= 0:
    return 1
  else:
    return 0

In [31]:
hidden=[0,0]
for i in range(len(sumv)):
  hidden[i]=Heaviside(sumv[i])

In [32]:
print(hidden)

[0, 0]


In [33]:
sumo=np.dot(hidden,W2)+B2[0]
y_pred=Heaviside(sumo)

In [34]:
print(y_pred)

0


In [38]:
y_pred=[]
for i in range(X.shape[0]):
  x=X[i]
sumv=summation(x,W11,W12,B1)
hidden=[0,0]
for i in range(len(sumv)):
  hidden[i]=Heaviside(sumv[i])
  sumo=np.dot(hidden,W2)+B2[0]
  y_pred.append(Heaviside(sumo))

In [39]:
 y_pred

[0, 0]